#!/usr/bin/expect -f


set force_conservative 1  ;# set to 1 to force conservative mode even if
                          ;# script wasn't run conservatively originally
if {$force_conservative} {
        set send_slow {1 .1}
        proc send {ignore arg} {
                sleep 1
                exp_send -s -- $arg
        }
}

set timeout -1
spawn centmin
expect "Enter option"
send -- "13\r"
expect "Enter option"
send -- "13\r"
expect "Enter option"
exp_send "\x03"